# this file is AI generated
apiVersion: v1
kind: SecurityPolicy
metadata:
  name: snpx-security-policy
  description: Security configuration for snpx containerized npm execution

# Package transport configuration
# Explicitly define which transport protocol specific packages use
package_transports:
  # MCP servers with HTTP transport
  "@modelcontextprotocol/server-http": "http"
  "@modelcontextprotocol/server-web": "http"
  
  # MCP servers with SSE transport
  "@modelcontextprotocol/server-events": "sse"
  "@modelcontextprotocol/server-streaming": "sse"
  
  # Override automatic detection for specific packages if needed
  "some-custom-package": "stdio"

spec:
  docker:
    capabilities:
      drop:
        - ALL
      add:
        - SETUID
        - SETGID
        - DAC_OVERRIDE
    
    security_opts:
      - no-new-privileges:true
      - seccomp:default
    
    user: "1000:1000"
    read_only_root_filesystem: false
    
    tmpfs:
      - /tmp:noexec,nosuid,size=100m
      - /var/tmp:noexec,nosuid,size=50m
    
    ulimits:
      nproc: 1024
      nofile: 65536
      fsize: 1073741824  # 1GB
    
    memory_limit: "512m"
    cpu_limit: "1.0"
    pids_limit: 256

  network:
    policy: "bridge"
    dns_servers:
      - "8.8.8.8"
      - "1.1.1.1"
    
    allowed_domains:
      - "registry.npmjs.org"
      - "github.com"
      - "api.github.com"
      - "nodejs.org"
    
    blocked_ports:
      - "22"
      - "3389"
      - "5432"
      - "3306"

  filesystem:
    mount_options:
      - ro
      - nodev
      - nosuid
      - noexec
    
    allowed_paths:
      - "/usr/local/lib/node_modules"
      - "/root/.npm"
      - "/tmp"
      - "/var/tmp"
    
    blocked_paths:
      - "/proc/sys"
      - "/sys/firmware"
      - "/dev/mem"
      - "/dev/kmem"

  runtime:
    timeout: "300s"
    max_restart_attempts: 3
    
    environment_whitelist:
      - "NODE_ENV"
      - "NPM_CONFIG_*"
      - "PATH"
      - "HOME"
      - "USER"
    
    signal_handling:
      graceful_shutdown_timeout: "10s"
      force_kill_timeout: "30s"

  audit:
    log_level: "info"
    log_commands: true
    log_network_access: false
    log_file_access: false  